name: FakeHat
version: 0.1.0012
description: Shows all users with a fake hat on their head
author: meiskam

main: org.shininet.bukkit.fakehat.FakeHat
database: false
depend: [ProtocolLib]

commands:
  FakeHat:
    description: used for config manipulation
    
permissions:
  fakehat:
    description: Gives all FakeHat permissions
    children:
      fakehat.config: true
  fakehat.config:
    description: Allows user to edit, save, or reload configs
    children:
      fakehat.config.get: true
      fakehat.config.set: true
  fakehat.config.get:
    description: Allows user to get configs
    default: op
  fakehat.config.set:
    description: Allows user to set or reload configs
    default: op
